const translates = {
	name: 'Nombre',
	active: 'Estado',
	created: 'Creado',
	id: 'ID',
	coordinador_type_rol: 'Tipo',
	person_name: 'Nombres',
	person_last_name: 'Apellidos',
	person_email: 'Correo electrónico',
	person_ci_number: 'Doc. Identidad',
	person_date_birth: 'Fecha de Nacimiento',
	person_address: 'Dirección',
	person_cellphone: 'Número de telefono',
	student_full_name: 'Nombre del Estudiante',
	program_name: 'Programa',
	matricula_gestion: 'Gestión',
	descripcion: 'Descripción',
	version: 'Versión',
	date_init: 'Fecha de Inicio',
	date_end: 'Fecha Fin',
	area_name: 'Area',
	teacher_full_name: 'Docente',
	path_front: 'Url Frontend',
	type: 'Sección',
	matricula_name: 'Matrícula',
	subject_name: 'Asignatura',
	qualification: 'Califcación Final',
	approved: 'Estado',
	person_full_name: 'Nombre Completo',
	sede: 'Sede',
	rol_name: 'Rol',
	user_name: 'Nombre',
	user_last_name: 'Apellidos',
	user_date_birth: 'Fecha de nacimiento',
	user_cellphone: 'Número de Celular',
	user_ci_number: 'Doc. Identificacion',
	user_username: 'Usuario',
	academics_hours: 'Horas Académicas',
	index: 'Nro',
	total_coordinadores: 'Total Coodinadores',
	start_time: 'Fecha Inicial',
	close_time: 'Fecha Final',
};

module.exports = {
	translates,
};
